name: backend
description: A Simple backend implemented using dart!
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: 
  dart_jsonwebtoken: ^2.4.1
  shelf: ^1.3.0
  shelf_router: ^1.1.2
